version: '3.9'

services:
  node_app:
    container_name: task_management_service
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - mongo
    command: npm run start
    ports:
      - 3000:3000
    networks:
      - backend
    restart: unless-stopped
  mongo:
    image: mongo
    container_name: mongodb
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DBNAME}
    ports:
      - 27017:27017
    networks:
      - backend
    restart: unless-stopped
networks:
  backend:
